server:
  port: 8080

spring:
  application:
    name: jobpilot

  datasource:
    url: jdbc:postgresql://ep-purple-moon-an3fofr2-pooler.c-6.us-east-1.aws.neon.tech:5432/jobpilot?sslmode=require
    username: neondb_owner
    password: npg_4SHUA3kdwvJD
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 1
      minimum-idle: 1
      idle-timeout: 30000
      connection-timeout: 20000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: karan.mandhare.qnopy@gmail.com
    password: vnevlsprwqwialmt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  jwt:
    secret: 404E635266556A586E32723575387882F413F4428472B4B6250645367566B5970
    expiration: 86400000

  ai:
    api-key: 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
    api-url: https://openrouter.ai/api/v1/chat/completions
    model: stepfun/step-3.5-flash:free

  cloudinary:
    cloud-name: ddosofdcr
    api-key: 241359566162918
    api-secret: KASLFJSKFLOIURISFJDLAFLKSJFDLSJFLAKSJFD;LSKF930420980SJKFDL


logging:
  level:
    org.springframework.core.env: DEBUG


frontend:
  url: http://localhost:4200
